name: CD - Generate Delivery Artifact

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ATV_Formativa.WebAPI/ATV_Formativa.WebAPI.sln

      - name: Publish project
        run: dotnet publish ATV_Formativa.WebAPI/ATV_Formativa.WebAPI.sln -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
