name: CI - Build & Test

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
     
      - name: Restore dependencies
        run: dotnet restore ATV_Formativa.WebAPI/ATV_Formativa.WebAPI.sln

      - name: Build
        run: dotnet build ATV_Formativa.WebAPI/ATV_Formativa.WebAPI.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ATV_Formativa.WebAPI/ATV_Formativa.WebAPI.sln --no-build --verbosity normal

    discord:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Notificação Discord
            if: always() 
            run: |
              status="✅ Build e testes passaram!"
              if [ "${{ needs.build.result }}" != "success" ]; then
                status="❌ Build ou testes falharam!"
              fi

              curl -H "Content-Type: application/json" \
                -X POST \
                -d "{\"content\": \"$status\n🔗 Repositório: ${{ github.repository }}\n▶️ Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
                ${{ secrets.DISCORD_WEBHOOK_URL }}