name: Run  Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ATV_Formativa.WebAPI/ATV_Formativa.WebAPI.sln

    - name: Build solution
      run: dotnet build ATV_Formativa.WebAPI/ATV_Formativa.WebAPI.sln --configuration Release

    - name: Run test
      run:  dotnet test ATV_Formativa.WebAPI/ATV_Formativa.WebAPI.sln --configuration Release --no-build --verbosity normal

